"""Assemble the drafted sections into one standalone document (Markdown, HTML, PDF).

There is no venue for this version, so the output is a self-contained report rather
than a conference/journal submission package: no IEEE template, no LaTeX.

What it does
------------
1. Reads `paper/draft/*.md` in filename order and strips the drafting comments.
2. Resolves `[bibkey]` and `[key1; key2]` markers into numbered citations, in order
   of first appearance, against `paper/refs.bib`. Every marker must resolve; an
   unknown key is a hard error, so a typo cannot silently vanish from the text.
3. Inserts the figures from `paper/figures/` at the end of their anchor sections,
   with the captions generated by `paper/make_figures.py`.
4. Emits a References list containing only works actually cited, plus a
   "Citation notes" appendix recording, per reference, how far it was verified --
   full text, abstract only, or publisher/preprint page. Abstract-only sources are
   listed explicitly rather than left implicit.
5. Renders to HTML and then to PDF via headless Chrome or Edge, if one is present.

Usage
-----
    python paper/assemble.py                # Markdown + HTML + PDF
    python paper/assemble.py --no-pdf       # skip the browser step
    python paper/assemble.py --check        # validate citations/anchors, write nothing

Outputs `paper/amr_hgt_gnn.{md,html,pdf}`.

Build-time dependencies, deliberately NOT added to requirements.txt (that file pins the
runtime environment the results were generated on, and nothing here touches the
pipeline): the `markdown` package for HTML rendering, and Chrome or Edge for the PDF.
Without either, the Markdown is still written and `--no-pdf` skips the browser step.
"""

from __future__ import annotations

import argparse
import datetime
import os
import re
import shutil
import subprocess
import sys
import tempfile

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DRAFT = os.path.join(REPO, "paper", "draft")
FIGDIR = os.path.join(REPO, "paper", "figures")
BIB = os.path.join(REPO, "paper", "refs.bib")
OUT_STEM = os.path.join(REPO, "paper", "amr_hgt_gnn")

TITLE = ("Predicting per-contact, per-gene horizontal transfer of antimicrobial "
         "resistance genes in an agent-based simulation")
SUBTITLE = "Draft, not submitted. No venue."

# How far each source was verified. Recorded in paper/citations.md and
# paper/gene_mechanism_audit.md section 4; mirrored here so the document can state
# it, and cross-checked against refs.bib at build time.
VERIFICATION = {
    "gbd2019amr": "publisher page and abstract",
    "gbd2021amr": "publisher page and abstract",
    "yaffe2020": "full text",
    "zhou2021": "full text",
    "nguyen2026amrgnn": "full text",
    "ellabaan2021": "abstract; its 2026 Author Correction read in full",
    "velickovic2018": "preprint page and abstract",
    "vonwintersdorff2016": "abstract",
    "partridge2018": "abstract",
    "brito2021": "abstract",
    "seoane2011": "abstract",
    "hellweger2016": "abstract",
    "krone2007": "abstract",
    "merkey2011": "abstract",
    "lardon2011": "abstract",
    "gorochowski2012": "abstract",
    "glushchenko2019": "abstract",
    "kim2022": "abstract",
    "donabauer2025": "abstract",
    "cuzon2010": "abstract",
    "dandrea2013": "abstract",
    "bonnin2012": "abstract",
    "dolejska2012": "abstract",
    "liu2016mcr": "abstract",
    "devirgiliis2009": "abstract",
    "boguslawska2009": "full text",
    "hooper2015": "full text",
    "strahilevitz2009": "abstract",
    "li2015efflux": "full text",
    "coyne2011": "abstract",
    "weigel2003": "abstract",
    "clark2005": "abstract",
}

# (figure stem, anchor heading), in DOCUMENT order. Each figure is inserted at the end
# of its anchor section, immediately before the next heading, and numbered by position
# here -- so the numbering cannot disagree with the order a reader meets them in.
FIGURES = [
    ("fig2_architecture", "## 3.5 Model"),
    ("fig4_model_comparison", "## 4.1 The GNN outperforms per-gene classical baselines"),
    ("fig3_ablation", "## 4.3 Where the signal comes from"),
    ("fig1_per_gene_auroc", "## 4.5 Per-gene discrimination"),
]


def read_sections() -> list:
    out = []
    for name in sorted(os.listdir(DRAFT)):
        if not name.endswith(".md"):
            continue
        with open(os.path.join(DRAFT, name), encoding="utf-8") as fh:
            body = fh.read()
        body = re.sub(r"<!--.*?-->", "", body, flags=re.S).strip()
        out.append((name, body))
    return out


def parse_bib(path: str) -> dict:
    with open(path, encoding="utf-8") as fh:
        raw = fh.read()
    entries = {}
    for match in re.finditer(r"@(\w+)\{([^,]+),(.*?)\n\}", raw, flags=re.S):
        kind, key, body = match.group(1), match.group(2).strip(), match.group(3)
        fields = {}
        for fm in re.finditer(r"(\w+)\s*=\s*\{(.*?)\}\s*,?\s*(?=\n\s*\w+\s*=|\s*$)",
                              body, flags=re.S):
            fields[fm.group(1).lower()] = " ".join(fm.group(2).split())
        entries[key] = {"kind": kind, **fields}
    return entries


def tidy(value: str) -> str:
    """Strip the LaTeX-isms our .bib uses for a plain-text/HTML rendering."""
    value = value.replace("--", "\u2013")
    value = re.sub(r"\{\\['`\"^~=.]\{?(\w)\}?\}", r"\1", value)
    value = re.sub(r"\\['`\"^~=.]\{?(\w)\}?", r"\1", value)
    value = value.replace("{\\v{c}}", "c").replace("{\\'c}", "c")
    value = value.replace("$\\beta$", "\u03b2").replace("\\&", "&")
    return value.replace("{", "").replace("}", "")


def format_reference(key: str, e: dict) -> str:
    authors = tidy(e.get("author", "")).replace(" and ", "; ")
    title = tidy(e.get("title", ""))
    year = e.get("year", "n.d.")
    if e["kind"].lower() == "inproceedings":
        venue = tidy(e.get("booktitle", ""))
        tail = f"{venue}, {year}."
        if e.get("eprint"):
            tail += f" arXiv:{e['eprint']}."
    else:
        venue = tidy(e.get("journal", ""))
        bits = [venue]
        if e.get("volume"):
            v = e["volume"] + (f"({e['number']})" if e.get("number") else "")
            bits.append(v)
        if e.get("pages"):
            bits.append(tidy(e["pages"]))
        tail = f"{', '.join(b for b in bits if b)}, {year}."
    sep = "" if authors.endswith(".") else "."
    out = f"{authors}{sep} {title}. {tail}"
    if e.get("doi"):
        out += f" doi:{e['doi']}"
    if e.get("note"):
        out += f" ({tidy(e['note'])})"
    return out


def resolve_citations(text: str, bib: dict) -> tuple:
    """Replace [key] / [key1; key2] with numbered citations, in first-use order."""
    keys = sorted(bib, key=len, reverse=True)
    pattern = re.compile(
        r"\[((?:" + "|".join(re.escape(k) for k in keys) + r")"
        r"(?:\s*;\s*(?:" + "|".join(re.escape(k) for k in keys) + r"))*)\]")
    order: list = []
    problems: list = []

    def repl(m):
        cited = [c.strip() for c in m.group(1).split(";")]
        nums = []
        for c in cited:
            if c not in bib:
                problems.append(f"unknown citation key: {c}")
                continue
            if c not in order:
                order.append(c)
            nums.append(order.index(c) + 1)
        return "[" + ", ".join(str(n) for n in nums) + "]"

    text = pattern.sub(repl, text)

    # Any surviving bracketed token that looks like a bibkey is a typo.
    for stray in re.finditer(r"\[([a-z][a-z0-9]*\d{4}[a-z0-9]*)\]", text):
        problems.append(f"unresolved citation marker: [{stray.group(1)}]")
    return text, order, problems


def load_captions() -> dict:
    """Map figure stem -> (title, caption body) from paper/figures/captions.md."""
    path = os.path.join(FIGDIR, "captions.md")
    if not os.path.exists(path):
        return {}
    with open(path, encoding="utf-8") as fh:
        raw = fh.read()
    out = {}
    blocks = re.split(r"<!--\s*fig:\s*(\S+?)\s*-->", raw)
    # blocks = [preamble, stem1, body1, stem2, body2, ...]
    for stem, body in zip(blocks[1::2], blocks[2::2]):
        body = body.strip()
        heading, _, rest = body.partition("\n")
        title = heading.lstrip("# ").strip()
        rest = re.split(r"\n<!--", rest)[0]
        out[stem] = (title, " ".join(rest.split()))
    return out


def insert_figures(text: str) -> tuple:
    problems = []
    caps = load_captions()
    for number, (stem, anchor) in enumerate(FIGURES, 1):
        label = f"Figure {number}"
        if anchor not in text:
            problems.append(f"figure anchor not found: {anchor!r} (for {stem})")
            continue
        png = os.path.join(FIGDIR, stem + ".png")
        if not os.path.exists(png):
            problems.append(f"missing figure file: {stem}.png "
                            "(run python paper/make_figures.py)")
            continue
        start = text.index(anchor)
        nxt = text.find("\n## ", start + len(anchor))
        nxt2 = text.find("\n# ", start + len(anchor))
        if nxt == -1 or (nxt2 != -1 and nxt2 < nxt):
            nxt = nxt2
        if nxt == -1:
            nxt = len(text)
        if stem not in caps:
            problems.append(f"no caption for {stem} in figures/captions.md "
                            "(is its <!-- fig: --> marker present?)")
            continue
        title, caption = caps[stem]
        block = (f"\n\n![{label}: {title}](figures/{stem}.png)\n\n"
                 f"**{label}. {title}.** {caption}\n")
        text = text[:nxt] + block + text[nxt:]
    return text, problems



def build(check_only: bool = False) -> int:
    bib = parse_bib(BIB)
    problems = [f"refs.bib key missing a verification level: {k}"
                for k in bib if k not in VERIFICATION]
    problems += [f"VERIFICATION lists a key not in refs.bib: {k}"
                 for k in VERIFICATION if k not in bib]

    sections = read_sections()
    body = "\n\n".join(text for _name, text in sections)

    body, fig_problems = insert_figures(body)
    problems += fig_problems

    body, order, cite_problems = resolve_citations(body, bib)
    problems += cite_problems

    if problems:
        print("FAILED:")
        for p in problems:
            print("  - " + p)
        return 1
    print(f"sections: {len(sections)}  citations resolved: {len(order)}  "
          f"figures: {len(FIGURES)}")

    today = datetime.date.today().isoformat()
    head = (f"# {TITLE}\n\n**{SUBTITLE}**  \n"
            f"Assembled {today} by `paper/assemble.py` from `paper/draft/`.  \n"
            "Every number is traceable to `paper/claims_to_numbers.md`; figures are "
            "regenerated from committed result files by `paper/make_figures.py`.\n\n"
            "---\n")

    refs = ["\n\n# References\n"]
    for i, key in enumerate(order, 1):
        refs.append(f"{i}. {format_reference(key, bib[key])}")
    refs_text = "\n".join(refs)

    abstract_only = [k for k in order if VERIFICATION[k].startswith("abstract")]
    notes = [
        "\n\n# Appendix A. Citation notes\n",
        "Every reference above was checked against the source itself, not merely "
        "confirmed to exist: author list, venue, year and DOI, and whether the source "
        "actually supports the claim it is cited for. The audit is recorded in "
        "`paper/citations.md` and, for gene transfer mechanisms, in "
        "`paper/gene_mechanism_audit.md`.\n",
        "Because this version has no submission deadline, sources whose full text sits "
        "behind a paywall were verified against their abstracts and are cited only for "
        "what those abstracts state. They are listed here so the distinction is on the "
        "record rather than implied.\n",
        "| # | Reference key | Verified against |",
        "|---|---|---|",
    ]
    for i, key in enumerate(order, 1):
        notes.append(f"| {i} | `{key}` | {VERIFICATION[key]} |")
    notes.append(
        f"\n{len(abstract_only)} of the {len(order)} cited sources were verified at "
        "abstract level only. Upgrading them to full text is listed as outstanding work "
        "in `paper/STATUS.md`.\n")
    uncited = sorted(set(bib) - set(order))
    if uncited:
        notes.append(
            "`paper/refs.bib` additionally holds "
            + ", ".join(f"`{k}`" for k in uncited)
            + " — sources verified during the gene-mechanism audit that the text does "
              "not cite. They are kept for that record and are deliberately absent from "
              "the reference list above.\n")

    md = head + body + refs_text + "\n".join(notes)

    if check_only:
        print("check only: no files written")
        return 0

    with open(OUT_STEM + ".md", "w", encoding="utf-8") as fh:
        fh.write(md)
    print(f"wrote {os.path.relpath(OUT_STEM + '.md', REPO)}")
    return md


CSS = """
@page { size: A4; margin: 20mm 18mm 18mm 18mm; }
body { font-family: "Charter","Georgia","Times New Roman",serif; font-size: 10.5pt;
       line-height: 1.5; color: #111; max-width: 46em; margin: 0 auto; }
h1 { font-size: 17pt; line-height: 1.25; margin: 1.6em 0 0.5em; page-break-after: avoid; }
h1:first-of-type { margin-top: 0; font-size: 19pt; }
h2 { font-size: 12.5pt; margin: 1.4em 0 0.4em; page-break-after: avoid; }
h3 { font-size: 11pt; margin: 1.1em 0 0.3em; page-break-after: avoid; }
p { margin: 0 0 0.62em; text-align: justify; hyphens: auto; }
table { border-collapse: collapse; width: 100%; margin: 0.9em 0; font-size: 8.8pt;
        page-break-inside: avoid; }
th, td { border: 1px solid #bbb; padding: 4px 6px; text-align: left;
         vertical-align: top; }
th { background: #f2f2f2; }
code { font-family: "Consolas","DejaVu Sans Mono",monospace; font-size: 0.87em;
       background: #f4f4f4; padding: 0 2px; }
img { max-width: 100%; display: block; margin: 0.8em auto 0.2em; }
blockquote { margin: 0.8em 0 0.8em 1.2em; padding-left: 0.8em;
             border-left: 3px solid #ccc; color: #333; }
ol, ul { margin: 0 0 0.62em; padding-left: 1.4em; }
li { margin-bottom: 0.22em; }
hr { border: none; border-top: 1px solid #ccc; margin: 1.2em 0; }
em { color: #222; }
"""


def to_html(md_text: str) -> str:
    import markdown
    html_body = markdown.markdown(
        md_text, extensions=["tables", "fenced_code", "sane_lists", "attr_list"])
    return (f"<!doctype html><html><head><meta charset='utf-8'>"
            f"<title>{TITLE}</title><style>{CSS}</style></head>"
            f"<body>{html_body}</body></html>")


def find_browser() -> str:
    for candidate in (
        shutil.which("chrome"), shutil.which("msedge"),
        r"C:\Program Files\Google\Chrome\Application\chrome.exe",
        r"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe",
        r"C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe",
        r"C:\Program Files\Microsoft\Edge\Application\msedge.exe",
        "/usr/bin/google-chrome", "/usr/bin/chromium",
    ):
        if candidate and os.path.exists(candidate):
            return candidate
    return ""


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true",
                    help="validate citations and figure anchors, write nothing")
    ap.add_argument("--no-pdf", action="store_true", help="skip the browser step")
    args = ap.parse_args()

    result = build(check_only=args.check)
    if isinstance(result, int):
        return result
    md = result

    html = to_html(md)
    with open(OUT_STEM + ".html", "w", encoding="utf-8") as fh:
        fh.write(html)
    print(f"wrote {os.path.relpath(OUT_STEM + '.html', REPO)}")

    if args.no_pdf:
        return 0
    browser = find_browser()
    if not browser:
        print("no Chrome/Edge found; skipping PDF. HTML is complete "
              "(open it and print to PDF).")
        return 0
    with tempfile.TemporaryDirectory() as tmp:
        cmd = [browser, "--headless", "--disable-gpu", "--no-sandbox",
               f"--user-data-dir={tmp}", "--no-pdf-header-footer",
               f"--print-to-pdf={OUT_STEM + '.pdf'}",
               "file:///" + (OUT_STEM + ".html").replace("\\", "/")]
        proc = subprocess.run(cmd, capture_output=True, text=True, timeout=180)
    if os.path.exists(OUT_STEM + ".pdf"):
        size = os.path.getsize(OUT_STEM + ".pdf")
        print(f"wrote {os.path.relpath(OUT_STEM + '.pdf', REPO)} ({size:,} bytes)")
        return 0
    print("PDF was not produced. Browser said:")
    print((proc.stderr or proc.stdout or "")[-800:])
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
