"""Generate the README's "at a glance" panel from committed result files.

Same discipline as `paper/make_figures.py`: nothing here is typed by hand or
recomputed from a simulation run. Every number is read out of

    ai/checkpoints/reseeded/lab_v2_grouped50_runsplit/results.json

verified against the value recorded in `paper/claims_to_numbers.md`, and only
then written into README.md between the BEGIN/END markers. If a number has
drifted the script writes nothing and exits non-zero.

The panel deliberately includes a result that did NOT come out in the project's
favour (S4, message passing). A summary panel that shows only the wins is a
marketing artifact, and the rest of this repository is not one.

    python paper/make_readme_panel.py            # verify, then rewrite the panel
    python paper/make_readme_panel.py --check     # verify only, write nothing

`--check` also fails if README.md's committed panel differs from what the
current results would produce, so a stale panel cannot survive in the tree.
"""
import argparse
import os
import re
import subprocess
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from paper.make_figures import (  # noqa: E402
    HEADLINE_SET, REPO, SRC_LABEL, close, load, subset_macro,
)

README = os.path.join(REPO, "README.md")
BEGIN = "<!-- BEGIN:at-a-glance (generated by paper/make_readme_panel.py) -->"
END = "<!-- END:at-a-glance -->"

# Recorded in paper/claims_to_numbers.md. Used only to verify what we read.
CLAIMED = {
    "S1_headline_gnn": (0.9676, 0.0076),
    "S2_gnn_5gene": (0.9805, 0.0021),
    "S2_rf_5gene": (0.9647, 0.0031),
    "S4_msg_passing_gain": (0.0065, 0.0086),
    "S6_ece": (0.0012, 0.0003),
    "n_graph_pairs": 1300,
    "n_edges": 6029316,
    "n_positives": 4763,
    "n_runs": 50,
    "n_scenarios": 5,
    "n_tests": 280,
}


def collected_tests() -> int:
    """Ask pytest how many tests exist, rather than asserting a number."""
    out = subprocess.run([sys.executable, "-m", "pytest", "-q", "--collect-only"],
                         cwd=REPO, capture_output=True, text=True, timeout=600).stdout
    m = re.search(r"(\d+) tests? collected", out)
    if not m:
        raise SystemExit("could not read a test count from pytest --collect-only")
    return int(m.group(1))


def check_prose(data: dict) -> list:
    """Guard the hand-written figure captions in README.md.

    The panel above is generated, so it cannot drift. The figure captions beside it
    are prose and contain literals -- the same shape as the hard-coded dataset hash
    that sat in make_figures.py through a whole reference-set change. We do not
    template the prose (it is argument, not a table), so instead we assert that each
    number it states still matches the live results and fail if one has moved.
    """
    problems = []
    with open(README, encoding="utf-8") as fh:
        # The prose uses typographic minus (U+2212); f-strings emit ASCII hyphen.
        text = fh.read().replace("−", "-")

    gm, gsd, _ = subset_macro(data, "gnn", HEADLINE_SET)
    rm, rsd, _ = subset_macro(data, "random_forest", HEADLINE_SET)
    pg = data["per_gene_auroc"]["gnn"]
    ab = data["ablation"]["No genomic genes"]["delta_vs_all"]

    required = {
        f"{gm:.4f} ± {gsd:.4f}": "S2 GNN (5 genes)",
        f"{rm:.4f} ± {rsd:.4f}": "S2 RF (5 genes)",
        f"{ab['mean']:.4f} ± {ab['sd']:.4f}": "S5 carried-gene ablation",
        f"acrAB-tolC {pg['acrAB-tolC']['mean']:.4f} ± {pg['acrAB-tolC']['sd']:.4f}":
            "S9 acrAB-tolC",
        f"vanA {pg['vanA']['mean']:.4f} ± {pg['vanA']['sd']:.4f}": "S9 vanA",
    }
    for literal, label in required.items():
        if literal not in text:
            problems.append(
                f"README figure caption is stale for {label}: expected the text "
                f"{literal!r}, which is not present")
    return problems


def check(data: dict, n_tests) -> list:
    """Verify every number the panel prints against claims_to_numbers.md."""
    problems = []

    def cmp(label, got_mean, got_sd, key):
        want_mean, want_sd = CLAIMED[key]
        if not close(got_mean, want_mean):
            problems.append(f"{label}: mean {got_mean!r} != claimed {want_mean}")
        if not close(got_sd, want_sd):
            problems.append(f"{label}: sd {got_sd!r} != claimed {want_sd}")

    def cmp_int(label, got, key):
        if got != CLAIMED[key]:
            problems.append(f"{label}: {got!r} != claimed {CLAIMED[key]}")

    s, ds = data["summary"], data["dataset"]
    cmp("S1 headline GNN", s["gnn"]["headline_auroc"]["mean"],
        s["gnn"]["headline_auroc"]["sd"], "S1_headline_gnn")
    cmp("S6 ECE", s["gnn"]["ece"]["mean"], s["gnn"]["ece"]["sd"], "S6_ece")

    gf = data["comparisons"]["gnn_minus_graph_free"]["diff"]
    cmp("S4 message passing", gf["mean"], gf["sd"], "S4_msg_passing_gain")

    gm, gsd, _ = subset_macro(data, "gnn", HEADLINE_SET)
    rm, rsd, _ = subset_macro(data, "random_forest", HEADLINE_SET)
    cmp("S2 GNN (5 genes)", gm, gsd, "S2_gnn_5gene")
    cmp("S2 RF  (5 genes)", rm, rsd, "S2_rf_5gene")

    cmp_int("graph pairs", ds["n_graph_pairs"], "n_graph_pairs")
    cmp_int("edges", ds["n_edges"], "n_edges")
    cmp_int("edge-gene positives", ds["n_edge_gene_positives"], "n_positives")
    cmp_int("scenarios", len(data["scenarios"]), "n_scenarios")

    runs = sum(len(v[k]) for v in data["split"]["runs_by_scenario"].values()
               for k in ("train", "val", "test"))
    cmp_int("runs", runs, "n_runs")
    if n_tests is not None:
        cmp_int("tests", n_tests, "n_tests")
    return problems


def panel(data: dict, n_tests) -> str:
    s, ds = data["summary"], data["dataset"]
    gnn, ece = s["gnn"]["headline_auroc"], s["gnn"]["ece"]
    gf = data["comparisons"]["gnn_minus_graph_free"]
    gm, gsd, gvals = subset_macro(data, "gnn", HEADLINE_SET)
    rm, rsd, rvals = subset_macro(data, "random_forest", HEADLINE_SET)
    ahead = sum(1 for a, b in zip(gvals, rvals) if a > b)
    n_runs = sum(len(v[k]) for v in data["split"]["runs_by_scenario"].values()
                 for k in ("train", "val", "test"))
    seeds = len(data["model_seeds"])
    tests = f"{n_tests} passing" if n_tests is not None else "see `pytest -q`"

    return f"""{BEGIN}
## At a glance

| | |
|---|---|
| **Predicting gene transfer** | Test AUROC **{gnn['mean']:.4f} ± {gnn['sd']:.4f}** over {seeds} model seeds, on held-out *simulation runs* the model never trained on (claim S1) |
| **Against a tuned baseline** | On the {len(HEADLINE_SET)} genes a per-gene random forest can be fitted to in every seed: GNN **{gm:.4f} ± {gsd:.4f}** vs RF **{rm:.4f} ± {rsd:.4f}**, GNN ahead on **{ahead} of {seeds} seeds** (claim S2) |
| **What the graph adds** | **Nothing we can measure.** Message passing moves the headline by **{gf['diff']['mean']:+.4f} ± {gf['diff']['sd']:.4f}**, positive in only **{gf['seeds_first_better']} of {gf['n_seeds']} seeds** — a spread that includes zero (claim S4) |
| **Calibration** | Expected calibration error **{ece['mean']:.4f} ± {ece['sd']:.4f}** (claim S6) |
| **Dataset** | **{ds['n_graph_pairs']:,}** graph pairs from **{n_runs}** simulation runs across **{len(data['scenarios'])}** scenarios — {ds['n_edges']:,} directed contacts, {ds['n_edge_gene_positives']:,} recorded transfer events |
| **Tests** | **{tests}**, including a byte-identity guard on the frozen `paper_v1` biology |

<sub>Generated by [`paper/make_readme_panel.py`](paper/make_readme_panel.py) from
[`{SRC_LABEL}`](ai/checkpoints/reseeded/lab_v2_grouped50_runsplit/), which re-checks every
value against [`paper/claims_to_numbers.md`](paper/claims_to_numbers.md) and fails on drift.
These are **within-simulation** results with no external validation — see
[Paper](#paper).</sub>
{END}"""


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="verify numbers and the committed panel; write nothing")
    ap.add_argument("--no-tests", action="store_true",
                    help="skip the pytest collection count (faster)")
    args = ap.parse_args()

    data = load()
    n_tests = None if args.no_tests else collected_tests()

    problems = check(data, n_tests) + check_prose(data)
    if problems:
        print("FAILED: panel numbers disagree with paper/claims_to_numbers.md:")
        for p in problems:
            print("  -", p)
        return 1
    print("self-check: all panel numbers match paper/claims_to_numbers.md")

    text = panel(data, n_tests)
    with open(README, encoding="utf-8") as fh:
        readme = fh.read()

    if BEGIN not in readme or END not in readme:
        print(f"FAILED: {README} has no at-a-glance markers")
        return 1
    start, stop = readme.index(BEGIN), readme.index(END) + len(END)
    current = readme[start:stop]

    if args.check:
        if n_tests is None:
            # Without a test count the panel renders a placeholder in that row, so
            # comparing it to the committed panel would report a false "stale".
            print("numbers verified; panel text not compared (--no-tests)")
            return 0
        if current != text:
            print("FAILED: README.md's at-a-glance panel is stale; "
                  "rerun without --check")
            return 1
        print("README.md's at-a-glance panel is up to date")
        return 0

    if current == text:
        print("README.md's at-a-glance panel already up to date")
        return 0
    with open(README, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(readme[:start] + text + readme[stop:])
    print("rewrote README.md's at-a-glance panel")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
